### PR TITLE
Implemented function to access the filter delay values

### PR DESCRIPTION
**Pull request by raui100**
I needed to access the filter delay values but there was no getter function.

### CODE REVIEW

**Comment by trueb2** [comment]
I would be fine with making the internal state pub like the coefficients. What do you think?

**Comment by raui100** [comment]
Making them public would also work for me :)

I stumbled upon the [_sosfilt32](https://github.com/qsib-cbie/sci-rs/blob/15613db9d110eac0cb9b7555f708bcd7e678348c/sci-rs/src/signal/filter/sosfilt.rs#L222C4-L222C14) function and was wondering why this function is faster. Could you explain this to me? I'm working on an SIMD IIR filter and would also implement performance improvements there.

**Comment by trueb2** [comment]
Nice, do you mind changing the PR to just making the members pub?

As for the sosfilt implementation, I use tiling cause the compiler to hoist, unroll, reorder and SIMD instructions. I have benchmarks for the sosfilt implementation because the faster the better for power consumption on embedded devices. If you manage to make the sosfilt function faster, I would love to know how. I chose the current implementation based on assembly generated while looking at godbolt.org and benchmarking. You should find that the near optimal instructions are emitted with this code.

I took a deep dive into the compiler generating the correct floating point instructions a while ago. I was benchmarking fma and floating point fast instructions to try to find the best option.

**Comment by raui100** [comment]
I have changed the PR to simply make the filter delay values public.

I had guessed that `TILE=4` in combination with `f32` tries to use some SIMD instructions. However I couldn't make sense of it. Filtering is inherently a sequentiel process and I really don't know where you could use SIMD to speed this up. I'd love to hear it though!

I'm using SIMD differently.  I have a `&[Simd<f32, 8>]` slice and the filter is implemented as `Filter<Simd<f32, 8>>`. If the CPU supports `AVX2` I can filter 8 signals at once, which is ~4 faster than `sosfiltfilt`. I haven't compared it against `_sosfilt32` yet though. 

I'll upload the library  with MIT/Apache 2.0 license eventually. I can ping you, if you're interested.

**Comment by trueb2** [comment]
Ah, okay. So we currently have this interface for the fastest single channel execution. This does tiling with some instruction reordering and as much SIMD as possible. However, it can't ever fully utilize the SIMD bandwidth because of the data dependencies in the biquad folding math.
```rust
///
/// A specialized cascaded Biquad filter for 32-bit floating point samples
///
/// Specializations
///  * Single-sided 4th and 8th order filters
///     * Example: 4th or 8th order lowpass Butterworth
///  * Double-sided 4th order filters are accelerated
///     * Example: 4th order bandpass Butterworth
///
pub fn sosfilt_fast32_st(y: &[f32], sos: &mut [Sos32], z: &mut [f32]) {
    _sosfilt32(y, sos, z);
}
```

If we adjust the interface to allow parallel filtering of additional channels, we could achieve higher performance. It may require explicit SIMD intrinsics, but right now we aren't giving the compiler a chance to optimize multi-channel filtering.

I will explore something along the lines of this interface:
```rust
///
/// A specialized cascaded Biquad filter for 32-bit floating point samples.
/// Channels are processed in a fashion that the compiler may interleave and
/// optimize SIMD and pipelining.
///
pub fn sosfilt_multi_fast32_st<const N: usize>(sos_y_z: &mut [(&[f32], &mut [Sos32], &mut [f32]); N]);
```

**Review by trueb2 — APPROVED** [review]

**Comment by trueb2** [comment]
Yes, we could do that for the floating point interface. For the isize interface, the input values are stored as isize (where the input data is of target bit-width). This is pretty common on a microcontroller where the ADC might sample integers that need to be filtered. We could support in-place filtering where the bit-widths match to minimize memory usage. We will have to be a little careful with the read/write access patterns.

**Comment by raui100** [comment]
Keeping a unified interface might be desirable...
And if the compiler can emit SIMD optimized code this way it might be superior to explicit SIMD code, where one might have to copy data in/out of the `Simd` struct. If you're open for a pair programming session I'd love to do that :) I have followed you on LinkedIn.

**Pull request merged**
